FORMAT: 1A
HOST: https://iot-sprinkler-scheduler.herokuapp.com/

# sprinkler-scheduler

sprinkler-scheduler is a simple API that allows users to ping scheduler. And Also read and change shedule

## Ping [/ping]



### Ping service [GET]
ping service and see if it is running


+ Response 200 (application/json)

        {
        "serviceStatus":"running"
        }
       

## Next  command time  [/houses/{house_id}/next_command_time]

+ Parameters
    + house_id (required, string, `1`)  House identifier

    
### Get next  command time[GET]


returns time of next command


+ Response 200 (application/json)

        {
        "time":"08:03:10 pm"
        }
    

## Schedule [/houses/{house_id}/schedule]

+ Parameters
    + house_id (required, string, `1`)  House identifier
   

### Get current schedule[GET]

retrieve current schedule of sprinkler scheduler

+ Response 200 (application/json)

        {
            "startMonth":4,
      
            "endMonth":10,
             "excluded":[
             {
                    "day":2,
                    "month":2,
                    "year":2016
                    }
                    ]
                    }

### Set new schedule [POST]

change the shcedule 

+ startMonth (number) - Arbitrary,  number of start month in schedule
+ endtMonth (number) - Arbitrary,  number of end  month in schedule
+ excluded (json) - Arbitrary,  json array representing dayes that will be excluded from schedule
+ Request (application/json)

            {
              "startMonth":4,
              "endMonth":10,
              "excluded":[
                {
                  "day":2,
                  "month":2,
                  "year":2016
                }
              ]

            }

+ Response 200(application/json)



##  Excluded [/huses/{house_id}/schedule/excluded]

+ Parameters
    + house_id (required, string, `1`)  House identifier
    
### Add excluded day [POST]

Add new day to excludes 

+ day (number) - Arbitrary, the number of day (starting from 1)
+ month (number) - Arbitrary, the number of month (starting from 1)
+ year (number) - Arbitrary, year

+ Request (application/json)

        {
             "day":2,
             "month":2,
             "year":2016
             }

+ Response 200 (application/json)