FORMAT: 1A
HOST: https://iot-sprinkler-scheduler.herokuapp.com/

# sprinkler-scheduler

sprinkler-scheduler is a simple API that allows users to ping scheduler and get last commang

## Ping [/ping]



### Ping service [GET]
ping service and see if it is running


+ Response 200 (application/json)

        {
        "serviceStatus":"running"
        }
       

## Last Command [/status]

### Get last Command [GET]

get status of sprinkler. (last command scheduler gave to it)


+ Response 200 (application/json)

        {
        "lastCommand":"true"
        }
    

## Schedule [/schedule]

### Get current schedule[GET]

retrieve current schedule of sprinkler scheduler

+ Response 200 (application/json)

        {
            "startMonth":4,
      
            "endMonth":10,
             "excluded":[
             {
                    "day":2,
                    "month":2,
                    "year":2016
                    }
                    ]
                    }

### Set new schedule [POST]

change the shcedule 

+ startMonth (number) - Arbitrary,  number of start month in schedule
+ endtMonth (number) - Arbitrary,  number of end  month in schedule
+ excluded (json) - Arbitrary,  json array representing dayes that will be excluded from schedule
+ Request (application/json)

            {
              "startMonth":4,
              "endMonth":10,
              "excluded":[
                {
                  "day":2,
                  "month":2,
                  "year":2016
                }
              ]

            }

+ Response 200(application/json)



##  Excluded [/schedule/excluded]

### Add excluded day [POST]

Add new day to excludes 

+ day (number) - Arbitrary, the number of day (starting from 1)
+ month (number) - Arbitrary, the number of month (starting from 1)
+ year (number) - Arbitrary, year

+ Request (application/json)

        {
             "day":2,
             "month":2,
             "year":2016
             }

+ Response 200 (application/json)